### PR TITLE
Aleks and Hao Aseembly Beta-test

### PR DESCRIPTION
**Pull request by AleksandarPetrov**
Some edits suggested after some TA beta-testing today:

- A small note on when attaching the motors
- A small note on which heat sink to use (I, of course, first put the wrong one)
- "Duckietown Hut" was used in the Raspberry Pi and Hut section. The actual board says "Duckiebot Hut", so I change it to that. 
- Removed "Finally, plug in the USB cables in the two micro USB ports." from Step 3 of the same section as there is a separate step for that: Step 5
- Added a remark that one can use the longer USB cables that came with the powerbank
- In "Raspberry Pi and top plate" added a note on not taking the M3 Nylon screws by mistake (I did that, and fun fact, after you screw one of these in, you can't get it out...)
- Step 2 of Chassis assembly: haven't edited it because I am not sure what's actually correct. When talking about left and right motor, is that when the bottom part is upright (motors under) or upside-down (motors above, as in fig 7.98)?
- Front bumper assembly: haven't changed anything but we noticed that if looking at the pictures it seems we have to partially disassemble the bot that we just assembled so that we can pass the electric F/F cables through the top chassis. It is possible without disassembling it, but the photo might be a bit confusing

### CODE REVIEW

**Comment by gibernas** [comment]
@aleksanndar1995 please fix line 4, I guess it should not be there.  For the Hut, @tanij which name should we use?

**Comment by aleksanndar1995** [comment]
> @aleksanndar1995 please fix line 4, I guess it should not be there. For the Hut, @tanij which name should we use?

My bad, I guess I pasted it by mistake, it's removed now.

**Comment by gibernas** [comment]
@AndreaCensi Should we maybe merge this before this afternoon?

**Comment by gibernas** [comment]
@tanij ?

**Pull request merged**
