### PR TITLE
updated instruction for python 3 in ubuntu 18

### PR DESCRIPTION
**Pull request by AmaurX**
@AndreaCensi I just passed my computer to ubuntu18, and following exactly those commands leads pip to use python2. With the updated commands here, everything goes fine.
@liampaull I think you are in charge of the book right?

### CODE REVIEW

**Comment by AndreaCensi** [comment]
@liampaull DRY principle would imply stripping out the installation instructions here and simply redirect to the Github README. Thoughts?

**Comment by liampaull** [comment]
Yes that's what we agreed.

**Comment by tanij** [comment]
@liampaull merge this or not?

**Comment by liampaull** [comment]
Not. let's just link to the README like we did in the docs-AIDO book.

**Comment by tanij** [comment]
@AmaurX see above

**Pull request closed without merging**
