### PR TITLE
Update 1_0_11_hw_assembly_db18.md

### PR DESCRIPTION
**Pull request by yetongumich**
Add instructions on how to mount the smaller heat sink.

### CODE REVIEW

**Comment by tanij** [comment]
@yetongumich please address the build failures to get this merged

**Comment by frank-qcd-qk** [comment]
This is fixed in the latest version

**Comment by liampaull** [comment]
@frank-qcd-qk so we should close?

**Comment by frank-qcd-qk** [comment]
> @frank-qcd-qk so we should close?

Yes

**Pull request closed without merging**
